---
language: objective-c
osx_image: xcode7.1
env:
  global:
  - secure: DE9IUM+pIV757GU0ccfDJhA752442pKu3DyBthrzHW9+GbsqbfuJOx045CYNN5vOWutFPC0A51B9WxhLNpXXqD3mfU8MhP1gkF7SskrHvcAPrCyfdqZf1Q8XDP5phm2KbHhhwxQMYmmicd6yj8DPNy2wRoSgPSDp/ZUDk51XZDU=
  - secure: ecj/PwpbHkH9AYFsc2TMeRuNm5E3xMM8A0x4AcGhzpwDuZWdFx3R1T4G9u45Z5aUyTJWGqOeX1JPaEVVFZuYnNBKRy0kmiUrM9EE0j7WsT57K48tP1ysn2ynyvHgbYkKOfYR0t8XAMWTBbulT9DVVk3DS69//2WgiXGDVUEJTyI=
  - numjobs=3
  - OSX=1
  - USE_CCACHE=2
  - CCACHE_SLOPPINESS=pch_defines,time_macros
  - CCACHE_COMPRESS=1
  - CCACHE_MAXSIZE=300M
  matrix:
  - MAKEFILE=1    URHO3D_LIB_TYPE=SHARED URHO3D_DEPLOYMENT_TARGET=generic
  - XCODE=1       URHO3D_LIB_TYPE=STATIC CMAKE_OSX_DEPLOYMENT_TARGET=10.11 SF_DEFAULT=mac:OSX-64bit-STATIC.tar.gz
  - XCODE=1       URHO3D_LIB_TYPE=SHARED CMAKE_OSX_DEPLOYMENT_TARGET=10.11
  - XCODE=1 IOS=1 URHO3D_LIB_TYPE=STATIC IPHONEOS_DEPLOYMENT_TARGET=9.1 sdk=iphonesimulator
    URHO3D_64BIT=0
  - XCODE=1 IOS=1 URHO3D_LIB_TYPE=STATIC IPHONEOS_DEPLOYMENT_TARGET=9.1 sdk=iphonesimulator
matrix:
  fast_finish: true
before_script:
- SECONDS=0
- export TRAVIS_COMMIT=$TRAVIS_COMMIT~
- export TAG=$(git describe --exact-match $TRAVIS_COMMIT 2>/dev/null); if [[ $TAG
  =~ [[:digit:]]+\.[[:digit:]]+ ]]; then export RELEASE_TAG=$TAG; fi
- export COMMIT_MESSAGE=$(git log --format=%B -n 1 $TRAVIS_COMMIT)
- if [ $XCODE ] && ([ $RELEASE_TAG ] || (! [[ $TRAVIS_BRANCH =~ [^-]+-[^-]+-CI ]]
  && echo $COMMIT_MESSAGE |grep -cq '\[ci package\]')); then export PACKAGE_UPLOAD=1;
  fi
- if [ $XCODE ] && echo $COMMIT_MESSAGE |egrep -cq '\[(ccache clear|xcode 64bit only)\]'; then export XCODE_64BIT_ONLY=1;
  fi
- travis_retry brew update >/dev/null
- which cmake >/dev/null 2>&1 || cmake=cmake
- if [ $PACKAGE_UPLOAD ]; then doxygen='doxygen graphviz'; fi
- travis_retry brew install ccache $cmake $doxygen
- export PATH=$(brew info ccache |grep -o '\S*lib\S*'):$PATH
- if [ $XCODE ]; then sudo cp -p $(which ccache) $(dirname $(xcodebuild -find-executable
  clang)) && for compiler in clang clang++; do path=$(xcodebuild -find-executable
  $compiler); sudo mv $path{,.orig} && sudo ln -sf $(dirname $path)/clang.orig /usr/bin/$compiler
  && sudo ln -sf ccache $path; done; sudo rm -rf /Applications/Xcode.app/Contents/Developer/Platforms/{AppleTV,Watch}{OS,Simulator}.platform;
  fi
- rake ci_setup_cache
script: ELAPSED=$SECONDS rake ci && if [ $PACKAGE_UPLOAD ]; then ELAPSED=$SECONDS
  rake ci_package_upload; fi
after_script:
- rake ci_teardown_cache
- if [ ${TRAVIS_JOB_NUMBER##*.} == 5 ]; then rake ci_delete_mirror; fi
notifications:
  email:
    on_success: never
    on_failure: change
    recipients:
    - weitjong@gmail.com
